### ISSUE TITLE
Climada-petals 5.0.0 not available on conda-forge (?)

### ISSUE THREAD

**Issue by bguillod** [CLIMADA-project/climada_petals#140]
I am not able to install climada-petals 5.0.0 in my conda environment: Installing climada-petals from conda-forge seem to always point to version 4.1.0, and requesting version 5.0.0 fails, for instance using:
```
conda install -c conda-forge climada-petals=5.0.0
```
raises:
```
PackagesNotFoundError: The following packages are not available from current channels:
  - climada-petals=5.0.0*
```

From a look at conda-forge (https://anaconda.org/conda-forge/climada-petals/files) I cannot find version `5.0.0`, but there are two version labelled as `4.1.0`, the latest one I suspect might be wrongly labelled as such instead of `5.0.0` (at least, from its date this is what it seems).

How can I install climada-petals `5.0.0` without cloning the repository?

Note that although I am using conda in the example above, I have previously set mamba as the solver, so I doubt this is the reason for this behaviour.

**Comment by peanutfun** [comment]
Climada Petals v5 had not been released. It is now, and v5.0.0 is available from conda-forge: https://anaconda.org/conda-forge/climada-petals
