### ISSUE TITLE
OSM: Test and test data seemingly inconsistent

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_petals#17]
The test `climada_petals.entity.exposures.test.test_openstreetmap.TestOSMFileQuery.test_retrieve_cis` fails with 

**Error Message**  `191 != 22`
**Stacktrace**
```
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/petals_branches/branches/develop/workspace/climada_petals/entity/exposures/test/test_openstreetmap.py", line 107, in test_retrieve_cis
    self.assertEqual(len(gdf), 22)
AssertionError: 191 != 22
```

The discrepancy is likely due to a bug/issue of a previous version of gdal:\
gdal 3.3 finds 191 items in the given file with the query involved where gdal 3.2 used to find only 22.

TODO: manually check the file to confirm that 191 is the right number. If so, adapt the test.

**Comment by Evelyn-M** [comment]
Verified that this was a bug, indeed, with gdal 3.2. Updating the environment (and gdal to 3.3) and amending the test to 191 found items instead of 22 hence solves this issue, indeed (visually inspected and concluded that the found items made sense). #23 corrects the respective test

**Comment by emanuel-schmid** [comment]
many thanks! 👍
