### ISSUE TITLE
cannot reproduce exposure tutorial / osm polygons are skipped 

### ISSUE THREAD

**Issue by SWILD-ISF** [CLIMADA-project/climada_petals#31]
Hi @Evelyn-M and @chahank 

not sure whether this it the right forum to ask a question but I'll try it anyway. 

I'm going through the climada-petals tutorial and in `climada_exposures_openstreetmap.ipynb` at the end of section 1.1 when forests are loaded with `retrieve` I only get 

> climada_petals.entity.exposures.openstreetmap.osm_dataloader - WARNING - skipped OSM feature 

so that the Geo Data Frame is empty afterwards. I haven't changed the code at all. I tried it with other queries and .pbf files as well but I'm getting the same. 

What I would actually like to do is loading buildings and assign each building a value. In case you have a way of doing this/code available any help will be very much appreciated. 

Thanks in advance, 
Simon (from FS)

**Comment by Evelyn-M** [comment]
Dear Simon

Thanks for reaching out! That is unexpected, indeed. I just re-ran the tutorial (on branch `develop`) and it still worked.
In general, the analogous code for retrieving buildings (around 650'000 results), would be this:

```
osm_keys = ['building']
osm_query = "building='yes' or 'building'"
gdf_buildings = HNDFileQuery.retrieve('multipolygons', osm_keys, osm_query)
```

Possibly, there is an issue with your gdal and/or ogr version, as it seems that the driver for the query isn't initialized in correctly in the `retrieve` function. Can you find which version you have installed?

Alternatively, if you're not running a huge query, you can also try the second approach described in the tutorial, loading directly from the overpass api.
Let me know how it's going!

Evelyn

**Comment by SWILD-ISF** [comment]
Hi Evelyn,

thanks for answering so quickly. And thanks for the code snippet with the buildings. 

I'm using the climada environment with Anaconda. The GDAL package there has version 3.4.0. I saw there is version 3.4.1 now but I don't think that would change anything. I'll try it nonetheless. 
I'm assuming GDAL contains both modules gdal and ogr in osgeo.
Maybe this helps:

```
Help on package osgeo:

NAME
    osgeo - # __init__ for osgeo package.

PACKAGE CONTENTS
    _gdal
    _gdal_array
    _gdalconst
    _gnm
    _ogr
    _osr
    gdal
    gdal_array
    gdalconst
    gdalnumeric
    gnm
    ogr
    osr
    utils

FUNCTIONS
    ver_str(ver)

DATA
    fail_on_unsupported_version = False
    gdal_ver = (3, 3)
    gdal_version = (3, 4, 0)
```

```
help(osgeo.ogr)

Help on module osgeo.ogr in osgeo:

NAME
    osgeo.ogr

DESCRIPTION
    # This file was automatically generated by SWIG (http://www.swig.org).
    # Version 3.0.12
    #
    # Do not make changes to this file unless you know what you are doing--modify
    # the SWIG interface file instead.
```

```
help(osgeo.gdal)

Help on module osgeo.gdal in osgeo:

NAME
    osgeo.gdal

DESCRIPTION
    # This file was automatically generated by SWIG (http://www.swig.org).
    # Version 3.0.12
```

Maybe it's worth mentioning that I'm using this all on Windows. Just tried it again, and it's unfortunately not working.

Thanks,
Simon

**Comment by Evelyn-M** [comment]
@emanuel-schmid, any ideas? Sounds like a Windows-related problem, potentially. I'm using the same versions on Mac.
