### ISSUE TITLE
event ids must be greater than zero

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_petals#45]
The plotting methods of hazard expect event ids to be greater than zero but this constraint is never checked.

Either change the arguable argument handling in the plotting methods and get rid of the somewhat obscure integer magic - or just include the constraint in the `check` method.

**Comment by emanuel-schmid** [comment]
#42

**Comment by peanutfun** [comment]
https://github.com/CLIMADA-project/climada_python/pull/546 adds a check for valid event IDs to the `Hazard.check` method.

**Comment by chahank** [comment]
With https://github.com/CLIMADA-project/climada_python/pull/546 this is solved.
