### ISSUE TITLE
Consolidate requirements with those of climada_python (core)

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_petals#65]
Climada Petals requires the Climada Core module. However, it has its very own requirement specifications, most of which are the same as in Climada Core. I propose to consolidate the requirements and only list the *additional*  requirements for Climada Petals in this repository. This should make it easier to maintain compatibility between the Petals and Core requirements.

**Comment by peanutfun** [comment]
@chahank @emanuel-schmid What do you think?

**Comment by emanuel-schmid** [comment]
The environment specs now simply require climada 3.3 which is compatible to 3.3.x-dev and 3.3.2 which in turn require Python 3.9.

**Comment by peanutfun** [comment]
Excellent work, thank you!
