### ISSUE TITLE
Latest Climada Core requirements incompatible to Petals requirements

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_petals#67]
After upgrading Core to Python 3.9 (https://github.com/CLIMADA-project/climada_python/pull/614) the environment specifications of the latest Core and Petals `develop` branches are incompatible. Core now requires Python 3.9, whereas Petals still requires Python 3.8. Can we simply upgrade to 3.9 here as well?

This relates to #65: Petals doubles many of the Core requirements. Potentially, any upgrade in the Core requirements may lead to such incompatibilities.

**Comment by emanuel-schmid** [comment]
The environment specs now simply require climada 3.3 which is compatible to 3.3.x-dev and 3.3.2 which in turn require Python 3.9.
