### ISSUE TITLE
`env_climada.yml` specs incompatible to editable pip installation of CLIMADA Core

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_petals#78]
`env_climada.yml` specifies `climada` as requirement for conda. Conda, however, is not aware of CLIMADA if it was installed via `pip`, especially if the install was editable (this is the case if one follows the [advanced install instructions](https://climada-python.readthedocs.io/en/latest/guide/install.html#advanced-instructions)). This leads to conda installing the conda CLIMADA package when updating the environment for Petals (see [instructions](https://climada-python.readthedocs.io/en/latest/guide/install.html#install-climada-petals-optional)). Therefore, the editable install is ignored and one is working with a stable version of CLIMADA Core again.

The update to `env_climada.yml` was done to remove all double-listed requirements, which is a very good thing. @emanuel-schmid Is it an issue to remove CLIMADA as requirement from `env_climada.yml`?

**Comment by aleeciu** [comment]
I would say it is not an issue - specifically because there can't be any `climada_petals` without `climada_python` so it's a bit of a redudant requirement imho. Is there a way of testing the presence of `climada_python` (editable version or not) upon the installation of petals and - if this is not present - just throw a message saying that petals is useless without main CLIMADA ?

**Comment by peanutfun** [comment]
The environment specs for conda are generally different from the required packages in the `setup.py`. There, we definitely require `climada`, and therefore Petals cannot be installed if Core is not present in the environment (independent from how it was installed). So there is no need for special error handling.

When we set up a conda package for Petals, we have to put the Core package into its dependencies as well. But this is part of the package recipe, not the environment specs here.

So I guess I'll simply remove `climada` from the specs here.

**Comment by emanuel-schmid** [comment]
Well - without climada in env_climada.yml all the other packages, that climada depends on, are missing, right?
So yes this is an issue 🧐 

It is not entirely true that conda is unaware of climada that has been installed with `pip -e`. At least it is listed when you run `conda list climada`.

@peanutfun What exactly do you want to achieve and how does it fail?

**Comment by emanuel-schmid** [comment]
Yes you're right. conda re-installs climada from conda-forge! (While the output of `conda list climada` remains the same 🙄)

I'll update the env_climada.yml file. together with the `script/jenkins/branches/Jenkinsfile`.

**Comment by peanutfun** [comment]
@emanuel-schmid This issue was fixed by https://github.com/CLIMADA-project/climada_petals/commit/37a86833181770d9f79a371e6559208378d60c97 but was re-introduced with https://github.com/CLIMADA-project/climada_petals/commit/2ea96f3a52042b856fbf5a900cb3207af7613b0b. Could you remove the `climada` requirements from the `climada_petals/requirements/env_climada.yml` again?

**Comment by emanuel-schmid** [comment]
What makes you think it was re-introduced?

**Comment by peanutfun** [comment]
This line: https://github.com/CLIMADA-project/climada_petals/blob/develop/requirements/env_climada.yml#L7

Adding `climada` to the `env_climada.yml` will cause conda to download the conda package instead of relying on a pip-installed version

**Comment by emanuel-schmid** [comment]
Er - no, it doesn't 🧐, not in general.
E.g. on jenkins, the environment for the petals tests is created like this:

```bash
mamba create -n petals_env python=3.9
mamba env update -n petals_env -f ~/jobs/climada_install_env/workspace/requirements/env_climada.yml
mamba env update -n petals_env -f requirements/env_climada.yml

source activate petals_env
python -m pip install -e ~/jobs/climada_install_env/workspace/[test]
python -m pip install -e "."
```

and there the climada modules are obviously editable:

```bash
(petals_env) jenkins:~$ python -c 'import climada; print(climada.__file__)'
/var/lib/jenkins/jobs/climada_install_env/workspace/climada/__init__.py
```

**Comment by emanuel-schmid** [comment]
Ah! I see. When the order is mixed like this:

```bash
mamba create -n petals_env python=3.9

mamba env update -n petals_env -f ~/jobs/climada_install_env/workspace/requirements/env_climada.yml
source activate petals_env
python -m pip install -e ~/jobs/climada_install_env/workspace/[test]

mamba env update -n petals_env -f requirements/env_climada.yml
python -m pip install -e "."
```
the editable installation is overwritten by the one from conda-forge?

**Comment by peanutfun** [comment]
Exactly! Thank you 🙌

**Comment by peanutfun** [comment]
I think we can close this issue, then.
