### ISSUE TITLE
Missing file required by the "climada_petals" installation guidelines

### ISSUE THREAD

**Issue by aleeciu** [CLIMADA-project/climada_petals#97]
Hi, 

based on the installation guidelines of petals (https://climada-python.readthedocs.io/en/latest/guide/install.html#install-climada-petals-optional), one should do (second command line of step 3):

`conda env update -n climada_env -f requirements/env_developer.yml
`

however, it seems to me there is no such `env_developer.yml` in the folder or am I missing something :-) ?

**Comment by peanutfun** [comment]
Correct! This was fixed in the latest version, see https://github.com/CLIMADA-project/climada_python/pull/786

**Comment by aleeciu** [comment]
cool, thanks
